title: Push to IPFS/Filecoin
description: >-
  This Add-On pushes the selected documents to IPFS and the Filecoin network
  via Estuary. Once the run is complete, you’ll be given a working IPFS address
  for the document, which will make it more resilient from outages and removals.


  **Warning**: Once you run this Add-On, you cannot remove the document from
  the IPFS and Filecoin networks! This action cannot be undone.
  [Learn more about Estuary](https://docs.estuary.tech/what-is-estuary) and
  [IPFS](https://docs.ipfs.io/concepts/what-is-ipfs/).
type: object
documents:
  - selected
  - query
properties: {}
version: 2
